version: '3'
services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - dockerNetwork

  redis:
    image: redis
    restart: always
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    volumes:
      - redis-data:/data
    networks:
      - dockerNetwork

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    env_file:
      - .env
  # nest-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   env_file:
  #     - .env
  #   environment:
  #     - POSTGRES_HOST=postgres
  #     - REDIS_HOST=redis
  #   ports:
  #     - '${PORT}:${PORT}'
  #     - '${WS_PORT}:${WS_PORT}'
  #   depends_on:
  #     - postgres
  #     - redis
  #   networks:
  #     - dockerNetwork

volumes:
  postgres:
  redis-data:
  rabbitmq:


networks:
  dockerNetwork:
    driver: bridge
