services:
  postgres:
    image: postgres
    restart: always
    env_file:
        - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    # no need for volumes, we don't need to persist data
    volumes:
      - redis-data:/data
volumes:
  postgres:
  redis-data: